services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./demo_medium.sql:/demo_medium.sql
    ports:
      - "5432:5432"

